from pathlib import Path
import os
from typing import Annotated
from uuid import UUID, uuid4

import httpx

from fastapi import (
    FastAPI,
    File,
    Form,
    HTTPException,
    Request,
    UploadFile,
)

from fastapi.responses import HTMLResponse, JSONResponse
from pydantic import BaseModel, Field
from fastapi.staticfiles import StaticFiles
from fastapi.templating import Jinja2Templates

# Database functions used to store and retrieve analysis information
from database import (
    complete_analysis,
    create_analysis as create_analysis_record,
    get_analysis as get_analysis_record,
    init_db,
    list_analyses,
    update_status,
)


# ============================================================
# APPLICATION CONFIGURATION
# ============================================================

# Get the directory where this Python file is located.
# This allows us to build absolute paths to templates and static files.
BASE_DIR = Path(__file__).resolve().parent


# Configure Jinja2 to load HTML templates from the "templates" folder.
templates = Jinja2Templates(
    directory=str(BASE_DIR / "templates")
)


# Create the FastAPI application.
app = FastAPI(title="Matchline ATS")


# Serve CSS, JavaScript, images, etc. from the "static" directory.
#
# Example:
# /static/css/style.css
#
# will point to:
# project/static/css/style.css
app.mount(
    "/static",
    StaticFiles(directory=str(BASE_DIR / "static")),
    name="static",
)


# ============================================================
# N8N CONFIGURATION
# ============================================================

# URL of the n8n webhook responsible for processing the
# resume and job description.
#
# The environment variable is used in production.
# If it is not defined, the default URL is used.
N8N_WEBHOOK_URL = os.getenv(
    "N8N_WEBHOOK_URL",
    "https://n8n-production-2387.up.railway.app/webhook/ats-resume-analysis",
)


# Initialize the local database when the application starts.
init_db()


# ============================================================
# PYDANTIC MODELS
# ============================================================

class AnalysisResult(BaseModel):
    """
    Represents the final result generated by the ATS analysis.

    This model defines the structure that n8n must send
    back to the FastAPI application.
    """

    # ATS score between 0 and 100
    score: int = Field(ge=0, le=100)

    # Overall classification/verdict
    verdict: str

    # Short explanation of the result
    summary: str

    # Positive aspects found in the resume
    strengths: list[str] = []

    # Missing skills, experience, or requirements
    gaps: list[str] = []

    # Suggestions for improving the resume
    recommendations: list[str] = []

    # Keywords from the job description found in the resume
    matched_keywords: list[str] = []

    # Keywords from the job description missing from the resume
    missing_keywords: list[str] = []


class AnalysisCallback(BaseModel):
    """
    Structure of the payload received from n8n
    when the analysis is completed.
    """

    # ID of the analysis that was processed
    analysis_id: UUID

    # Current status of the analysis
    status: str = "completed"

    # Actual ATS analysis result
    result: AnalysisResult


# ============================================================
# HTML PAGES
# ============================================================

@app.get("/", response_class=HTMLResponse)
async def landing_page(request: Request):
    """
    Render the application's home page.
    """

    return templates.TemplateResponse(
        request=request,
        name="index.html",
        context={
            "active_page": "home"
        },
    )


@app.get("/analyze", response_class=HTMLResponse)
async def analyze_page(request: Request):
    """
    Render the resume analysis page.

    This is the page where the user can upload
    their resume and enter a job description.
    """

    return templates.TemplateResponse(
        request=request,
        name="analyze.html",
        context={
            "active_page": "analyze",
            "submitted": False,
        },
    )


@app.get("/results/{analysis_id}", response_class=HTMLResponse)
async def results_page(
    request: Request,
    analysis_id: UUID,
):
    """
    Render the results page for a specific analysis.

    The analysis_id is passed to the frontend so that
    it knows which analysis result to retrieve.
    """

    return templates.TemplateResponse(
        request=request,
        name="results.html",
        context={
            "active_page": "results",
            "analysis_id": str(analysis_id),
        },
    )


@app.get("/account", response_class=HTMLResponse)
async def account_page(request: Request):
    """
    Render the account/history page.

    The page receives the user's previous analyses
    from the local database.
    """

    return templates.TemplateResponse(
        request=request,
        name="account.html",
        context={
            "active_page": "account",

            # Retrieve all previous analyses
            "analyses": list_analyses(),
        },
    )


# ============================================================
# ANALYSIS FORM
# ============================================================

@app.post("/analyze", response_class=HTMLResponse)
async def submit_analysis(
    request: Request,

    # Job description entered by the user
    job_description: Annotated[str, Form()] = "",

    # Uploaded resume
    resume: UploadFile | None = File(default=None),
):
    """
    Handle the HTML form submission.

    This endpoint currently renders the same page again
    with information about the submitted resume/job description.
    """

    return templates.TemplateResponse(
        request=request,
        name="analyze.html",
        context={
            "active_page": "analyze",

            # Indicates that the form was submitted
            "submitted": True,

            # Keep the job description available to the template
            "job_description": job_description,

            # Display the uploaded file name
            "resume_name": resume.filename if resume else None,
        },
    )


# ============================================================
# CREATE ANALYSIS / SEND TO N8N
# ============================================================

@app.post("/api/analyses")
async def create_analysis(
    # Job description submitted as multipart form data
    job_description: Annotated[str, Form()],

    # Resume uploaded as a file
    resume: Annotated[UploadFile, File()],
):
    """
    Create a new ATS analysis.

    The workflow is:

        User
          ↓
        FastAPI
          ↓
        Save analysis in database
          ↓
        Send resume + job description to n8n
          ↓
        n8n processes the analysis
          ↓
        n8n calls the callback endpoint
          ↓
        FastAPI stores the final result
    """

    # --------------------------------------------------------
    # Validate job description
    # --------------------------------------------------------

    if not job_description.strip():
        raise HTTPException(
            status_code=422,
            detail="job_description is required",
        )


    # --------------------------------------------------------
    # Validate resume
    # --------------------------------------------------------

    if not resume.filename:
        raise HTTPException(
            status_code=422,
            detail="resume is required",
        )


    # Only PDF resumes are accepted.
    allowed_types = {
        "application/pdf"
    }

    if resume.content_type not in allowed_types:
        raise HTTPException(
            status_code=415,
            detail="Upload a PDF resume",
        )


    # --------------------------------------------------------
    # Generate a unique ID for this analysis
    # --------------------------------------------------------

    analysis_id = uuid4()


    # Read the uploaded PDF into memory.
    resume_bytes = await resume.read()


    # --------------------------------------------------------
    # Save initial analysis record
    # --------------------------------------------------------

    # Store the analysis in the local database before
    # sending it to n8n.
    create_analysis_record(
        str(analysis_id),
        resume.filename,
        job_description,
    )


    # --------------------------------------------------------
    # Prepare data for the n8n webhook
    # --------------------------------------------------------

    # Regular form fields sent to n8n.
    form_data = {
        "analysis_id": str(analysis_id),
        "job_description": job_description,
    }


    # Uploaded PDF file sent to n8n.
    files = {
        "resume": (
            resume.filename,
            resume_bytes,
            resume.content_type
            or "application/octet-stream",
        )
    }


    # --------------------------------------------------------
    # Send the analysis request to n8n
    # --------------------------------------------------------

    try:

        # Create an asynchronous HTTP client.
        async with httpx.AsyncClient(timeout=30) as client:

            # Send the job description and resume
            # to the n8n webhook.
            response = await client.post(
                N8N_WEBHOOK_URL,
                data=form_data,
                files=files,
            )

            # Raise an exception if n8n returns an HTTP error.
            response.raise_for_status()


    except httpx.HTTPError as error:

        # If communication with n8n fails,
        # mark the analysis as failed.
        update_status(
            str(analysis_id),
            "failed",
        )

        # Return a 502 Bad Gateway because FastAPI
        # could not communicate with the external n8n service.
        raise HTTPException(
            status_code=502,
            detail="Could not queue analysis in n8n",
        ) from error


    # --------------------------------------------------------
    # Mark the analysis as processing
    # --------------------------------------------------------

    update_status(
        str(analysis_id),
        "processing",
    )


    # --------------------------------------------------------
    # Return response to frontend
    # --------------------------------------------------------

    # 202 means the request was accepted,
    # but the analysis is still being processed.
    return JSONResponse(
        status_code=202,
        content={
            "analysis_id": str(analysis_id),

            "status": "processing",

            # Frontend can use this URL to poll
            # the current analysis status.
            "status_url": f"/api/analyses/{analysis_id}",
        },
    )


# ============================================================
# RECEIVE RESULT FROM N8N
# ============================================================

@app.post("/api/analyses/{analysis_id}/result")
async def receive_analysis_result(
    analysis_id: UUID,
    callback: AnalysisCallback,
):
    """
    Callback endpoint used by n8n.

    Once n8n finishes analyzing the resume,
    it sends the structured result back to this endpoint.

    Example flow:

        n8n
         ↓
        POST /api/analyses/{analysis_id}/result
         ↓
        Validate analysis
         ↓
        Save result in database
         ↓
        Return success
    """

    # --------------------------------------------------------
    # Check whether the analysis exists
    # --------------------------------------------------------

    analysis = get_analysis_record(
        str(analysis_id)
    )

    if analysis is None:
        raise HTTPException(
            status_code=404,
            detail="Analysis not found",
        )


# Make sure the callback ID matches the URL ID

    if callback.analysis_id != analysis_id:
        raise HTTPException(
            status_code=400,
            detail="analysis_id does not match callback URL",
        )


    # Save the completed analysis

    complete_analysis(
        str(analysis_id),
        callback.status,
        callback.result.model_dump(),
    )


    # Confirm that the result was successfully stored.
    return {
        "ok": True,
        "analysis_id": str(analysis_id),
        "status": callback.status,
    }


# GET ANALYSIS HISTORY

@app.get("/api/analyses")
async def get_analyses():
    """
    Return all analyses stored in the local database.

    This endpoint is used by the account/history page
    or frontend JavaScript.
    """

    return {
        "analyses": list_analyses()
    }


# GET A SINGLE ANALYSIS

@app.get("/api/analyses/{analysis_id}")
async def get_analysis(
    analysis_id: UUID,
):
    """
    Retrieve the current status or final result
    of a specific analysis.

    The frontend can repeatedly call this endpoint
    while the analysis is being processed.

    Example:

        processing
            ↓
        processing
            ↓
        completed + result
    """

    # Retrieve analysis from the database.
    analysis = get_analysis_record(
        str(analysis_id)
    )


    # If the ID does not exist, return 404.
    if analysis is None:
        raise HTTPException(
            status_code=404,
            detail="Analysis not found",
        )


    # Return the current analysis information.
    return analysis